version: '3.7'

services:
  dashboard:
    build:
      context: ./
    container_name: dam-dash
    restart: always
    ports:
      - 5000:80
    networks:
      - network

networks:
  network:
    driver: bridge
